### ISSUE TITLE
The composer install command is missing

### ISSUE THREAD

**Issue by f-wehrhausen** [ratepay/php-sdk#2]
Hello, 
unfortunately the package-name is missing in the composer command. Can you please add to it? On packagist I could only find the following package: https://packagist.org/packages/ratepay/php-library This, however, apparently from another author (and does not bear the same name).

**Comment by MartinKuhl** [comment]
Hi @f-wehrhausen our SDK is only a companion of examples. If you need the predefined functions  and classes, please use the Ratepay-Library.

**Comment by MartinKuhl** [comment]
fixed in new version 0.9.4.0
